export const fields = {
	feed: [
		['dc:publisher', 'publisher'],
		['dc:creator', 'author'],
		['dc:source', 'source'],
		['dc:title', 'title'],
		['dc:type', 'type'],
		'author',
		'title',
		'description',
		'link',
		['language', 'lang'],
		'copyright',
		['id', 'etag'],
		'etag',
		['date', 'updatedAt'],
		['lastBuildDate', 'updatedAt'],
	],
	item: [
		'link',
		['dc:language', 'lang'],
		'title',
		['dc:title', 'title'],
		['dc:date', 'createdAt'],
		['date', 'createdAt'],
		['published', 'createdAt'],
		['updated', 'updatedAt'],
		['dc:rights', 'copyright'],
		['dc:creator', 'author'],
		'author',
		'summary',
		['content:encoded', 'content'],
		'comments',
	],
	image: [
		['enclosure', 'enclosure', { keepArray: true }],
		'image',
		'media:thumbnail',
		'media:content',
		'media:group',
		'itunes:image',
		['content:encoded', 'content'],
	],
}
