export const fields = {
	feed: [
		'title',
		'description',
		'link',
		'atom:link',
		['language', 'lang'],
		'copyright',
		'id',
		'etag',
		'image',
		['date', 'updatedAt'],
		['updated', 'updatedAt'],
		['lastBuildDate', 'updatedAt'],
		['dc:title', 'title'],
		['dc:description', 'description'],
		['dc:source', 'source'],
		['dc:date', 'updatedAt'],
		['dc:language', 'lang'],
		['dc:rights', 'copyright'],
		['syn:updateBase', 'updatedAt'],
	],
	item: [
		'id',
		['guid', 'id'],
		['link', 'url'],
		'title',
		'author',
		'description',
		'category',
		['date', 'createdAt'],
		['published', 'createdAt'],
		['pubDate', 'createdAt'],
		['updated', 'updatedAt'],
		['dc:title', 'title'],
		['dc:creator', 'author'],
		['dc:subject', 'category'],
		['dc:description', 'description'],
		['dc:source', 'source'],
		['dc:date', 'updatedAt'],
		['dc:language', 'lang'],
		'summary',
		'content',
		['content:encoded', 'content'],
		'comments',
		['itunes:author', 'author'],
		['itunes:category', 'category'],
		['itunes:summary', 'description'],
		['media:group', 'group'],
	],
	image: [
		'image',
		['itunes:image', 'image'],
		'media:thumbnail',
		'media:content',
		'media:group',
		['enclosure', 'enclosure'],
		['enc:enclosure', 'enclosure'],
		['description', 'content'],
		['dc:description', 'content'],
		'content',
		['content:encoded', 'content'],
	],
	meta: [
		['itunes:duration', 'duration'],
		['itunes:explicit', 'explicit'],
		['itunes:subtitle', 'subtitle'],
		['itunes:season', 'season'],
		['itunes:episode', 'episode'],
		['itunes:episodeType', 'episodeType'],
		['itunes:keywords', 'keywords'],
		['media:group', 'group'],
	],
}
