const mapItunesField = f => [`itunes:${f}`, f]

export const fields = {
	feed: [
		['dc:publisher', 'publisher'],
		['dc:creator', 'author'],
		['dc:source', 'source'],
		['dc:title', 'title'],
		['dc:type', 'type'],
		'author',
		'title',
		'description',
		'date',
		['link', 'url'],
		['language', 'lang'],
		'copyright',
		'etag',
		'lastBuildDate',
	],
	item: [
		['dc:creator', 'author'],
		'author',
		['dc:date', 'date'],
		'date',
		['dc:language', 'lang'],
		['dc:rights', 'copyright'],
		['dc:title', 'title'],
		'title',
		['link', 'url'],
		'summary',
		['content:encoded', 'content:encoded', { includeSnippet: true }],
		'enclosure',
		'comments',
		'image',
		'thumbnail',
		'media:thumbnail',
		'media:group',
		'media:content',
		'itunes:image',
	],
	podcastFeed: ([
		'author',
		'subtitle',
		'summary',
		'explicit',
	]).map(mapItunesField),
	podcastItem: ([
		'author',
		'subtitle',
		'summary',
		'explicit',
		'duration',
		'image',
		'episode',
		'image',
		'season',
		'keywords',
		'episodeType',
	]).map(mapItunesField),
}
